version: '3.9'

services:
  vitalisdb:
    image: postgres:16.3
    container_name: vitalisdb

    restart: "no"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vitalis
      PGDATA: /var/lib/postgresql/data

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - vitalis-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: vitalis-pgadmin

    restart: "no"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vitalis.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - vitalisdb

    networks:
      - vitalis-network

volumes:
  postgres_data:

# rodar antes: docker network create vitalis-network
networks:
  vitalis-network:
    external: true
